name: macos

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"

jobs:
  test_mac:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macOS-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        auto-activate-base: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch>=1.0.0 -q
        pip install -e .[develop] --progress-bar off
        pip install sphinx==2.4.4
        pip install m2r
        git config --global credential.interactive never
        git config --global credential.modalprompt false
    - name: Test with pytest
      shell: bash -l {0}
      run: GIT_TERMINAL_PROMPT=0 pytest tests
